### ISSUE TITLE
Dashboard Administrador

### ISSUE THREAD

**Issue by JRBARROZ** [Murielson/SGM#48]
Eu como Administrador necessito ter noção do que está havendo no sistema em geral.
Segue abaixo uma lista de necessidades que eu mais preciso 👍 .

- [x] Todas as interações com atas em relações a monitores
- [x] Acesso a relatórios finais dos alunos em ordem de período
- [x] Poder ver o perfil de cada aluno 
- [x] Poder gerar PDFS em tudo o que tiver relação com documentos

Mais ideias são bem vindas!
Segue a baixo uma ideia de como deveria ser mais ou menos : 
https://colorlib.com/polygon/notika/index.html

**Comment by lilialnas** [comment]
Como **administrador do sistema de monitoria** quero **acompanhar o uso do sistema pelos usuários** para **verificar alguma coisa.**.
